In [3]:
import pandas as pd
df = pd.read_csv('..\\Desktop\\urban data\\Urban Data Hackathon\\UTSEUS-MOBIKE-shanghai_full.csv')

In [4]:
df.columns

Index(['orderid', 'bikeid', 'userid', 'start_time', 'start_location_x',
       'start_location_y', 'end_time', 'end_location_x', 'end_location_y',
       'track'],
      dtype='object')

In [5]:
start_location_x = input("start_location_x: ")
start_location_y = input("start_location_y: ")

start_location_x: 121.39
start_location_y: 31.28

In [6]:

def best_location(start_location_x, start_location_y):
    return df[(df['start_location_x'] == float(start_location_x) ) & (df['start_location_y']  == float(start_location_y))  ].groupby(['end_location_x', 'end_location_y'])['userid'].count().sort_values(ascending=False).reset_index().ix[0]

best_location(start_location_x, start_location_y)

end_location_x    121.392
end_location_y     31.269
userid              1.000
Name: 0, dtype: float64

In [48]:
print(df.shape)
A = df[['start_location_x', 'start_location_y']].join(df[:500].dropna().apply(lambda r: best_location(r['start_location_x'], r['start_location_y']),1).rename(columns=dict(userid='recommendations'))).sort_values(by='recommendations', ascending=False)

(1023603, 10)

In [8]:
A

,start_location_x,start_location_y,end_location_x,end_location_y,recommendations
166,121.317,31.309,121.322,31.298,116.0
261,121.374,31.313,121.373,31.322,86.0
102,121.469,31.325,121.483,31.320,65.0
197,121.532,31.330,121.531,31.323,62.0
181,121.311,31.237,121.320,31.240,61.0
285,121.529,31.333,121.531,31.323,60.0
215,121.413,31.276,121.422,31.274,37.0
115,121.490,31.317,121.485,31.319,36.0
290,121.554,31.287,121.553,31.280,35.0
216,121.411,31.289,121.416,31.293,34.0
81,121.322,31.259,121.319,31.241,32.0
280,121.322,31.259,121.319,31.241,32.0
294,121.314,31.246,121.319,31.241,31.0
206,121.476,31.283,121.482,31.282,28.0
54,121.513,31.311,121.508,31.312,27.0
223,121.423,31.264,121.430,31.266,27.0
281,121.457,31.319,121.447,31.318,27.0
286,121.476,31.303,121.484,31.305,27.0
85,121.527,31.324,121.531,31.323,26.0
75,121.313,31.245,121.319,31.241,26.0
204,121.493,31.282,121.490,31.276,26.0
213,121.442,31.313,121.447,31.318,26.0
9,121.442,31.313,121.447,31.318,26.0
218,121.411,31.288,121.416,31.293,25.0
252,121.311,31.239,121.320,31.240,24.0
282,121.411,31.272,121.422,31.274,24.0
6,121.441,31.228,121.445,31.224,24.0
17,121.414,31.272,121.423,31.273,23.0
256,121.301,31.308,121.322,31.296,23.0
106,121.436,31.332,121.440,31.331,22.0
...,...,...,...,...,...
1023573,121.451,31.246,NaN,NaN,NaN
1023574,121.462,31.313,NaN,NaN,NaN
1023575,121.498,31.341,NaN,NaN,NaN
1023576,121.402,31.266,NaN,NaN,NaN
1023577,121.415,31.172,NaN,NaN,NaN
1023578,121.429,31.218,NaN,NaN,NaN
1023579,121.474,31.262,NaN,NaN,NaN
1023580,121.497,31.261,NaN,NaN,NaN
1023581,121.435,31.267,NaN,NaN,NaN
1023582,121.450,31.325,NaN,NaN,NaN
1023583,121.532,31.297,NaN,NaN,NaN
1023584,121.515,31.291,NaN,NaN,NaN
1023585,121.410,31.283,NaN,NaN,NaN
1023586,121.445,31.154,NaN,NaN,NaN
1023587,121.473,31.290,NaN,NaN,NaN
1023588,121.297,31.312,NaN,NaN,NaN
1023589,121.452,31.260,NaN,NaN,NaN
1023590,121.446,31.283,NaN,NaN,NaN
1023591,121.405,31.266,NaN,NaN,NaN
1023592,121.403,31.238,NaN,NaN,NaN
1023593,121.481,31.345,NaN,NaN,NaN
1023594,121.470,31.259,NaN,NaN,NaN
1023595,121.386,31.314,NaN,NaN,NaN
1023596,121.486,31.271,NaN,NaN,NaN
1023597,121.366,31.242,NaN,NaN,NaN
1023598,121.452,31.336,NaN,NaN,NaN
1023599,121.437,31.239,NaN,NaN,NaN
1023600,121.518,31.291,NaN,NaN,NaN
1023601,121.532,31.298,NaN,NaN,NaN
1023602,121.367,31.104,NaN,NaN,NaN

In [51]:
from geojson import LineString, Feature, FeatureCollection
import geojson

A_cut = A[:300]
featureCollection = []
print(dir(featureCollection))
for row in A_cut.values:
    line = LineString([(row[0], row[1]), (row[2], row[3])])
    feature = Feature(geometry = line, properties={"recommendations": row[4]})
    featureCollection.append(feature)

featureCollection = FeatureCollection(featureCollection)

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']

In [52]:
geojson.dump(featureCollection, open('geo4.json', "w"))